Algoritmo "aumento de salário"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/02/2023
Var
// Seção de Declarações das variáveis 
 sal,aum:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva("salário atual")
 leia(sal)

aum<-sal*1.25
Fimalgoritmo